### ISSUE TITLE
Vertice count increases drastically on import

### ISSUE THREAD

**Issue by Excludos** [karl-/pb_Stl#11]
An object which Blender tells me have 12k vertices somehow ends up with 70k vertices after using this script to import it to Unity. With Unity's 65k max vertices count pr mesh this is an obvious problem, not to mention performance in general.

**Comment by karl-** [comment]
The dramatic increase is likely due to the STL format splitting each triangle into discrete vertices. During export to STL instead of coincident vertices sharing a single vertex (like Blender is probably doing), each vertex referenced by a triangle becomes distinct.

To fix this on the import side we could define an option to import smoothed normals, and therefore share coincident vertices.

**Comment by Excludos** [comment]
That would be excellent. Just tested with another object with 8500 vertices, and after import ended up with 49500 vertices, nearly 6x as much. This would give us a roof of 11300 vertices pr mesh instead of the intended 65534.

**Comment by karl-** [comment]
I've started work on this in a the `package` branch. Installing the lib is a little different now, instead of putting the code in your `Assets` directory, instead just clone the repository in the `Project/Packages` directory.

**Comment by karl-** [comment]
> Can I request an option to choose the mesh indexformat? So one can more easily set mesh.indexFormat to IndexFormat.UInt32 (Or even better, change it automatically if vertice count > 65k)? 

Sounds like a great idea, can you open a new issue for it?

**Comment by Thomas-6freedom** [comment]
Hello @karl- did you merge your package branch into the master ? Is this issue closed ? Thank you
